name: Pull Request CI

on:
  workflow_dispatch:
  push:
    branches: [develop, main]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: "cache"
        uses: actions/cache@v2
        with:
          path: |
            ~/.yarn
            ~/node_modules
            **/node_modules/**
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Installing dependencies
        run: yarn install --immutable

      - name: "hardhat compile"
        run: yarn run compile

      - name: "hardhat test"
        run: yarn run test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: testresult.xml
